### ISSUE TITLE
[BUG]: `node_to_symbolic` errors even though SymbolicUtils.jl is loaded

### ISSUE THREAD

**Issue by StevenWhitaker** [MilesCranmer/SymbolicRegression.jl#368]
### What happened?

I ran the following code (almost exactly copy-pasted from different sections of the README):
```julia
using SymbolicRegression, SymbolicUtils

X = randn(2, 100)
y = 2 * cos.(X[2, :]) + X[1, :] .^ 2 .- 2

options = Options(
    binary_operators=[+, *, /, -],
    unary_operators=[cos, exp],
    populations=20,
    save_to_file = false
)

hall_of_fame = equation_search(
    X, y, niterations=40, options=options,
    parallelism=:multithreading
)

dominating = calculate_pareto_frontier(hall_of_fame)

eqn = node_to_symbolic(dominating[end].tree)
```

Result:
```
ERROR: Please load the `SymbolicUtils` package to use `node_to_symbolic`.
```

Since SymbolicUtils *is* loaded, I did not expect to see this error.

### Version

v0.24.5

### Operating System

Linux

### Interface

Julia REPL

### Relevant log output

```shell
(jl_0elvPY) pkg> st
Status `/tmp/jl_0elvPY/Project.toml`
  [8254be44] SymbolicRegression v0.24.5 ⚲
⌃ [d1185830] SymbolicUtils v1.7.1
```

**Comment by StevenWhitaker** [comment]
I just tested with
```
(jl_0elvPY) pkg> st
Status `/tmp/jl_0elvPY/Project.toml`
  [8254be44] SymbolicRegression v1.0.0 `https://github.com/MilesCranmer/SymbolicRegression.jl.git#v1.0.0-beta4`
⌃ [d1185830] SymbolicUtils v3.4.1
```
and the code ran as expected. So I guess this issue is resolved, but not on an official release yet.

**Comment by MilesCranmer** [comment]
> ERROR: Please load the `SymbolicUtils` package to use `node_to_symbolic`.

If SymbolicUtils is loaded and this error still appears, it could be because there was an error during the precompilation or something else, which prevented the extension from loading. This might happen for example if you load SymbolicUtils from a different environment from the one SymbolicRegression is loaded in, for example. It could be a bug too!

If you see it again, can you try running `Base.retry_load_extensions()`? You can also write `err` for a more detailed backtrace, if it does error.

**Comment by MilesCranmer** [comment]
Ah, I just tried, and I get the same error!

Ok, so the reason is that `node_to_symbolic` is specifically for the new API in 1.0.0 – this is what is present on the README. The old API you would also need to pass the options, like this:

```julia
eqn = node_to_symbolic(dominating[end].tree, options)
```

Then it should work!

Sorry for the confusion. I am late in releasing 1.0.0, there are just some things I want to make sure are ready before it's up.

**Comment by StevenWhitaker** [comment]
Great, that did it. Thank you!

**Comment by joshkamm** [comment]
I just ran into a related problem and saw this issue while checking to see if it had already been reported. I think my actual problem was that I wasn't passing the correct arguments to symbolic_to_node, but the error message was about SymbolicUtils not being loaded which led me in the wrong direction. So I was able to get past the issue, but a more accurate error message would be helpful for the next person. Here's a simplified example:

<img width="403" alt="{310B7736-D937-4C16-8A37-703250AC26D8}" src="https://github.com/user-attachments/assets/c21dc519-4cbf-4d28-b7bb-1e5e75bacde9">

**Comment by MilesCranmer** [comment]
Good point! Yes it would be better to give a MethodError here if it’s actually loaded.

**Comment by MilesCranmer** [comment]
I think this is largely fixed FYI. The equation search returns Expression objects which can be passed normally to `node_to_symbolic`

**Comment by MilesCranmer** [comment]
I can run the example in the first post now
